variables:
  NODE_OPTIONS: --max-old-space-size=2560

.cache:
  cache:
    key: ${CI_COMMIT_REF_SLUG}-npm-dependency
    paths:
      - node_modules/
    policy: pull

.image:
  image: registry.gitlab.com/savushkin.i/environment/builder:alpine

stages:
  - Building dependency
  - Building libraries and linting projects
  - Building and testing projects
  - Publish artifacts
  - Deploy artifacts

include:
  - project: savushkin.i/environment
    ref: master
    file: templates/gitlab-ci/job-templates/npm-job-templates.yml

Linting Commit Message:
  stage: Building libraries and linting projects
  extends:
    - .image
    - .cache
  script:
    - echo "$CI_COMMIT_MESSAGE" | $(npm bin)/commitlint

Linting Angular Projects:
  stage: Building libraries and linting projects
  extends:
    - .image
    - .cache
  script:
    - make -f /opt/makefiles/Makefile.monorepo-angular lint

Common Building Angular Libraries:
  stage: Building libraries and linting projects
  extends:
    - .image
    - .cache
  dependencies: []
  before_script:
    - npm run ci:build:before_script --if-present
  script:
    - make -f /opt/makefiles/Makefile.monorepo-angular build
  after_script:
    - npm run ci:build:after_script --if-present
  artifacts:
    expire_in: 30 days
    paths:
      - dist/@ngx-library/

Production Building Angular Libraries:
  stage: Building libraries and linting projects
  extends:
    - .image
    - .cache
  dependencies: []
  before_script:
    - npm run ci:build:before_script --if-present
  script:
    - make -f /opt/makefiles/Makefile.monorepo-angular build-producation
  after_script:
    - npm run ci:build:after_script --if-present
  artifacts:
    expire_in: 30 days
    paths:
      - dist/@ngx-library/

Testing Angular Projects:
  stage: Building and testing projects
  services:
    - name: selenium/standalone-chrome:latest
      alias: selemium-standalone-chrome
  extends:
    - .image
    - .cache
  variables:
    SELENIUM_HOST: selemium-standalone-chrome
    SELENIUM_PORT: 4444
  dependencies:
    - Common Building Angular Libraries
  before_script:
    - npm run ci:test:before_script --if-present
  script:
    - make -f /opt/makefiles/Makefile.monorepo-angular test
  after_script:
    - npm run ci:test:after_script --if-present
    - make -f /opt/makefiles/Makefile.coverage
  coverage: '/Statements.*?(\d+(?:\.\d+)?)%/'
  artifacts:
    reports:
      junit:
        - junit-report/**/TESTS*.xml
    expire_in: 30 days
    when: always
    paths:
      - coverage/

Semantic Release:
  stage: Publish artifacts
  extends:
    - .image
    - .cache
  variables:
    GIT_STRATEGY: clone
    GITLAB_URL: https://$CI_SERVER_HOST
    GIT_AUTHOR_NAME: $GITLAB_USER_NAME
    GIT_AUTHOR_EMAIL: $GITLAB_USER_EMAIL
    GIT_COMMITTER_NAME: Medzoom Staff
    GIT_COMMITTER_EMAIL: medzoom-staff@medindex.ru
    NPM_CONFIG_REGISTRY: https://$NPM_REGISTRY_URL
    NPM_TOKEN: $NPM_REGISTRY_TOKEN
  dependencies:
    - Production Building Angular Libraries
  when: manual
  before_script:
    - npm run ci:publish:before_script --if-present
  script:
    - $(npm bin)/semantic-release --repository-url "${CI_REPOSITORY_URL}"
  after_script:
    - npm run ci:publish:after_script --if-present
